# conf/base/parameters.yml

data_split_options:
  test_size: 0.2
  random_state: 42

features:
  categorical:
    - Age Group          
    - Occupation
    - Marital Status
    - Education Level
    - Credit Default
    - Personal Loan
    - Contact Method
    - Housing Loan
  numeric:
    - Campaign Calls     
    - PreviouslyContacted
    - WasContactedBefore


model_hyperparameters:
  logreg:
    max_iter: 500
    class_weight: balanced
  random_forest:
    n_estimators: 300
    max_depth: 12
    min_samples_split: 5
    class_weight: balanced
  gradient_boosting:
    learning_rate: 0.05
    n_estimators: 300
    max_depth: 3
  xgboost:
    n_estimators: 600
    learning_rate: 0.04
    max_depth: 4
    subsample: 0.9
    colsample_bytree: 0.9
    eval_metric: logloss

evaluation_thresholds: [0.28, 0.32, 0.35]